package com.oop;

/**
 * @CONSTRUCTOR

 * 
 *              1.constructor is a block similar to method having same name that
 *              of class name
 * 
 *              2.doesn't have any return type not even void(as we need constructor for initializing the object
 *              so there is no need to return and also the default  constructor created by 
 *              compiler cannot decide what to return 
 * 
 *              3.the only modifiers applicable for constructor are public
 *              protected,default and private
 * 
 *              4.it executes automatically when we create an object
 *              
 *              
 *              
 *          ****************** Types **************************
 *
 *          1.default(no-arg) generated by compiler
 *          
 *          2.no-arg(user defined) 
 *          
 *          3.parameterized
 * 
 * 
 * 			
 * 			
 * 
 */

import java.util.Scanner;

public class Demo2 {
	public static void main(String[] args) {

		System.out.println("Enter your age");
		Scanner scanner = new Scanner(System.in);
		String name = scanner.nextLine();

		System.out.println("Enter your id");
		int id = scanner.nextInt();

		Employee e1 = new Employee(name, id);
		Employee e2 = new Employee(name, id);

		System.out.println(e1);
		System.out.println(e2);

		scanner.close();

	}

}

class Employee {
	String name;
	int id;

	public Employee(String name, int id) {
		this.name = name;
		this.id = id;

	}

	@Override
	public String toString() {
		return "Employee [name=" + name + ", id=" + id + "]";
	}

}
